version: '3.9'
services:
  db:
    image: postgres:16
    container_name: otakuplay-db
    environment:
      POSTGRES_USER: ${DB_USER:-otaku}
      POSTGRES_PASSWORD: ${DB_PASS:-otaku}
      POSTGRES_DB: ${DB_NAME:-otakuplay}
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER:-otaku} -d ${DB_NAME:-otakuplay} -p 5432']
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: otakuplay-api
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_SSL: 'false'
      PORT: 3000
    ports:
      - '3000:3000'
    restart: unless-stopped

volumes:
  pg_data:
